stages:
  - build
  - deploy
build test-frontend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - npm install --progress=false
    - npm run build
    - docker build -t test-frontend .

deploy test-frontend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - cd /opt/frontend
    - docker-compose down
    - docker-compose up -d
