stages:
  - build
  - deploy

build test-frontend:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - frontlatest
  script:
    - docker build -t test-frontend .

deploy test-frontend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - frontlatest
  script:
    - mkdir -p ~/frontend
    - rm -rf ~/frontend/*
    - cp -r 0302-frontend/. ~/frontend