version: "3.7" # optional since v1.27.0
services:
  frontend:
    image: test-frontend:frontlatest
    container_name: frontend
    restart: always
    ports:
      - '8081:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'